# Render.com deployment configuration for The Genius Frontend
# Updated: 2025-01-21 - Corrected for static site deployment
services:
- type: web
  name: genius-frontend
  runtime: static
  rootDir: web-app
  buildCommand: pnpm install --frozen-lockfile && pnpm run build
  staticPublishPath: dist
  envVars:
    - key: NODE_VERSION
      value: "18"
    - key: PNPM_VERSION
      value: "8"
    - key: NODE_ENV
      value: production
    - key: VITE_BACKEND_URL
      value: https://genius-backend-nhl3.onrender.com
  routes:
    - type: rewrite
      source: /api/*
      destination: https://genius-backend-nhl3.onrender.com/:splat
  headers:
    - path: /assets/*
      name: Cache-Control
      value: max-age=31536000, immutable
    - path: /*
      name: X-Frame-Options
      value: DENY
    - path: /*
      name: X-Content-Type-Options
      value: nosniff