# Render.com deployment configuration
# Updated: 2025-06-02 - Fixed pnpm build command
services:
- type: web
  name: genius-frontend
  buildCommand: pnpm install --frozen-lockfile && pnpm run build
  staticPublishPath: dist
  routes:
    - type: rewrite
      source: /api/*
      destination: https://genius-backend-nhl3.onrender.com/:splat
  headers:
    - path: /*
      name: Cache-Control
      value: max-age=31536000, immutable