services:
- type: web
  runtime: static
  name: genius-frontend
  buildCommand: npm ci && npm run build
  staticPublishPath: dist
  envVars:
    - key: NODE_VERSION
      value: "22"
  routes:
    - type: rewrite
      source: /api/*
      destination: https://genius-backend-nhl3.onrender.com/:splat
  headers:
    - path: /*
      name: Cache-Control
      value: max-age=31536000, immutable
