services:
- type: web
  runtime: static
  name: genius-frontend
  buildCommand: pnpm install --frozen-lockfile && pnpm config set auto-install-peers true && pnpm run build
  staticPublishPath: dist
  envVars:
    - key: NODE_VERSION
      value: "22"
    - key: PNPM_VERSION
      value: "9"
    - key: NODE_ENV
      value: production
    - key: VITE_BACKEND_URL
      value: https://genius-backend-nhl3.onrender.com
  routes:
    - type: rewrite
      source: /api/*
      destination: https://genius-backend-nhl3.onrender.com/:splat
  headers:
    - path: /*
      name: Cache-Control
      value: max-age=31536000, immutable
